config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :breeds

  resources :dogs, only: [:index]

  resources :users, only: [:index] do
    resources :dogs do
      resources :photos, only: [:new, :create]
    end
  end

  root 'home#index'

  get 'buscar_ubicacion' => 'dogs#select_location'
  put 'ubicacion' => 'dogs#set_location'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :dogs
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user
  validates :name, :age,
    :description, :particular_signals, :breed_id, presence: {message: "Campo requerido"}
  validates :age, length: {
    maximum: 50, minimum: 5, message: "El valor debe estar entre 5 y 50 letras"
  }
  validates :name, length: {minimum: 2, maximum: 15, message: "El valor debe estar entre 2 y 15 letras"}
  validates :particular_signals, length: {minimum: 5, maximum: 60, message: "El valor debe estar entre 5 y 60 letras"}
  validates :description, length: {minimum: 5, maximum: 200, message: "El valor debe estar entre 5 y 200 letras"}
  belongs_to :breed
  has_many :photos
  scope :recents, -> {Dog.last(15)}
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :dog
  has_attached_file :photo,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :styles => {
		  :medium => ["600x*>", :jpg], :mini => ["60x60#", :jpg]
    },
    :convert_options => {
      :mini => "-quality 50 -strip",
      :medium  => "-quality 85 -strip"
      }


  # Validate content type
  validates_attachment :photo,
  :content_type => { :content_type => ["image/jpeg", "image/jpg", "image/gif",
  	"image/png"]
  }
  # Validate filename
  validates_attachment_file_name :photo, :matches => [/png\Z/,/PNG\Z/,
   /JPG\Z/, /JPE?G\Z/, /jpe?g\Z/]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :dogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :phone
    devise_parameter_sanitizer.for(:sign_up) << :email
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_in) << :username
  end

end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: [:show, :edit, :update, :destroy]

  # GET /breeds
  # GET /breeds.json
  def index
    @breeds = Breed.all
  end

  # GET /breeds/1
  # GET /breeds/1.json
  def show
  end

  # GET /breeds/new
  def new
    @breed = Breed.new
  end

  # GET /breeds/1/edit
  def edit
  end

  # POST /breeds
  # POST /breeds.json
  def create
    @breed = Breed.new(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to @breed, notice: 'Breed was successfully created.' }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeds/1
  # PATCH/PUT /breeds/1.json
  def update
    respond_to do |format|
      if @breed.update(breed_params)
        format.html { redirect_to @breed, notice: 'Breed was successfully updated.' }
        format.json { render :show, status: :ok, location: @breed }
      else
        format.html { render :edit }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1
  # DELETE /breeds/1.json
  def destroy
    @breed.destroy
    respond_to do |format|
      format.html { redirect_to breeds_url, notice: 'Breed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breed
      @breed = Breed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breed_params
      params.require(:breed).permit(:name)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy, :select_location]
  before_action :set_user, only: [:new, :create]
  before_action :authenticate_user!, only: [:create, :new, :edit]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = @user.dogs.new(dog_params)
      if @dog.save
        #if params[:photos]
          #params[:photos].first.each do |photo|
            #@dog.photos.create(photo: photo[1])
          #end
        #end
        redirect_to new_user_dog_photo_path(@user, @dog)
      else
        render :new
      end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def select_location
  end

  def set_location

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @user = current_user
      @dog = Dog.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :age, :description, :particular_signals, :lat, :lng, :breed_id,)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @recents_dogs = Dog.recents
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_dog, only: [:new, :create]
  def new
    @photo = @dog.photos.new
  end

  def create
    if params[:photos]
      params[:photos].first.each do |photo|
        @dog.photos.create(photo: photo[1])
      end
    end
    redirect_to user_dog_path(@user, @dog)
  end

  private
  def set_dog
    @user = current_user
    @dog = @user.dogs.find(params[:dog_id])
  end

  def photos_params
    params.require(:dog).permit(:photos[])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
  def get_breeds
    Breed.all.order(:name)
  end

  def get_first_photo(dog)
    if dog.photos.count>0
      image_tag dog.photos.first.photo.url(:mini)
    else
      "No hay foto"
    end

  end

  def is_user_logged
    if user_signed_in?
      link_to "Poner en adopcion", new_user_dog_path(current_user.id), class: "btn btn-success big_button btn_white_font"
    else
      link_to "Poner en adopcion", new_user_registration_path, class: "btn btn-success big_button btn_white_font"
    end
  end
end

app/views/breeds/_form.html.erb
<%= form_for(@breed) do |f| %>
  <% if @breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
      <% @breed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breeds/edit.html.erb
<h1>Editing breed</h1>

<%= render 'form' %>

<%= link_to 'Show', @breed %> |
<%= link_to 'Back', breeds_path %>

app/views/breeds/index.html.erb
<h1>Listing breeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breeds.each do |breed| %>
      <tr>
        <td><%= breed.name %></td>
        <td><%= link_to 'Show', breed %></td>
        <td><%= link_to 'Edit', edit_breed_path(breed) %></td>
        <td><%= link_to 'Destroy', breed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breed', new_breed_path %>

app/views/breeds/new.html.erb
<h1>New breed</h1>

<%= render 'form' %>

<%= link_to 'Back', breeds_path %>

app/views/breeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @breed.name %>
</p>

<%= link_to 'Edit', edit_breed_path(@breed) %> |
<%= link_to 'Back', breeds_path %>

app/views/dogs/_form.haml
.container
  .row
    .col-md-12
      = form_for [@user, @dog], :html => { :role => "form", :multipart => true, id: "new-dog", class: "new_dog dropzone"}, validate: true do |f|
        - if @dog.errors.any?
          #error_explanation
            %h2
              = pluralize(@dog.errors.count, "error")
              prohibited this dog from being saved:
            %ul
              - @dog.errors.full_messages.each do |message|
                %li= message
        .row
          .col-md-5
            .form-group
              Nombre del perro
              %br/
              = f.text_field :name, class: "form-control"

            .form-group
              Edad del perro
              %br/
              = f.text_field :age, class: "form-control"

            .form-group
              Señas Particulares

              %br/
              = f.text_field :particular_signals, class: "form-control"
          .col-md-7

            .form-group
              Breve descripción acerca de tu mascota

              %br/
              = f.text_area :description, class: "form-control", placeholder: "Puedes describir brevemente como es tu mascota o las razones por las cuales lo pones en adopción"



            .form-group
              = f.label :breed_id
              %br/
              = f.collection_select :breed_id, get_breeds, :id, :name, include_blank: false



            .form-actions
              = f.submit 'Ponerlo en adopcion', class: "btn btn-success btn_white_font", id: "sbmtbtn"
              = link_to 'Cancelar', dogs_path, class: "btn btn-danger btn_white_font"
        .row
          .col-md-12
            %h4 Selecciona tu ubicacion
            #map{:style => "width: 100%; height: 500px;"}
            =f.hidden_field :lat
            =f.hidden_field :lng
            -#%input.form-control{:type => "hidden", name: "lat", id: "lat"}
            -#%input.form-control{:type => "hidden", name: "lng", id: "lng"}

        -#.photos
          -#%h4 Sube hasta 5 fotos de tu perro para que los usuarios lo conozcan
          -##dropzonePreview
          -#%br

:javascript
  $(document).ready(function(){
    var dog = #{@dog.to_json}
    getLocation(dog);    // form map for new view (print nothing with possibility of put marker)
    Dropzone.options.newDog = {
      //autoDiscover = false,
      autoProcessQueue: false,
      uploadMultiple: true,
      parallelUploads: 5,
      maxFiles: 5,
      previewsContainer: '#dropzonePreview',
      paramName: "photos[]",

      // The setting up of the dropzone
      init: function() {
        var myDropzone = this;
            //now we will submit the form when the button is clicked

            $("#sbmtbtn").on('click',function(e) {
              e.preventDefault();
              e.stopPropagation();
              $("input").trigger("focusout");
              if ($(".field_with_errors").length >= 1)
              {
                 console.log("Corrige todos los errores antes de continuar");
              }else{
                if (myDropzone.getQueuedFiles().length > 0){
                   myDropzone.processQueue();
                 }else{
                   $("#new-dog").submit();
                 }
              }// this will submit your form to the specified action path
              // after this, your whole form will get submitted with all the inputs + your files and the php code will remain as usual
        //REMEMBER you DON'T have to call ajax or anything by yourself, dropzone will take care of that
            });

          } // init end
    };

  });

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<h1>Listing dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Description</th>
      <th>Particular signals</th>
      <th>Owner name</th>
      <th>Owner email</th>
      <th>Owner phone</th>
      <th>Password</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Breed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.age %></td>
        <td><%= dog.description %></td>
        <td><%= dog.particular_signals %></td>
        <td><%= dog.owner_name %></td>
        <td><%= dog.owner_email %></td>
        <td><%= dog.owner_phone %></td>
        <td><%= dog.password %></td>
        <td><%= dog.lat %></td>
        <td><%= dog.lng %></td>
        <td><%= dog.breed.name %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.haml
.container
  %h2 Dar de alta un perro para adopcion
  %p
    Puedes dar de alta un perro para adopcion inmediatamente o puedes
    =link_to "registrate aqui", "#"
    para tener mas control sobre tus publicaciones
  = render 'form'

app/views/dogs/select_location.haml
.container
  %h3 Selecciona tu ubicacion
  #mensajes

  = form_tag("/set_location", method: "put") do |f|
    / map div
    #map{:style => "width: 1200px; height: 500px;"}
    %input.form-control{:type => "hidden", name: "lat", id: "lat"}
    %input.form-control{:type => "hidden", name: "lng", id: "lng"}
    %button.btn.btn-success{:type => "button", :type => 'submit'} Esablecer

  :javascript
    $(document).ready(function(){
      var dog = #{@dog.to_json}
      getLocation(dog);    // form map for new view (print nothing with possibility of put marker)
    });

app/views/dogs/show.haml
.container
  %p#notice= notice
  %p
    %strong Nombre:
    = @dog.name
  %p
    %strong Edad:
    = @dog.age
  %p
    %strong Descripcion:
    = @dog.description
  %p
    %strong Senas particulares:
    = @dog.particular_signals
  %p
    %strong Raza:
    = @dog.breed.name
  -@dog.photos.each do |photo|
    %br
    = image_tag photo.photo.url(:mini)

app/views/home/index.haml
.header_index
  .container
    .content_header
      %h2
        Bienvenido a Llevame Contigo
        .small LLevame Contigo es un proyecto que busca unir a las personas que bucan adoptar y dar en adopcion a perros
%br
%br
.container
  .row
    .col-md-8
      .table-responsive
        %h3 Perros recientemente puestos en adopcion
        %table.table.table-striped.table-hover
          %thead
            %tr
              %th Nombre
              %th Edad
              %th Raza
              %th Foto
              %th Conocelo
          %tbody
            -@recents_dogs.each do |dog|
              %tr
                %td
                  =dog.name
                %td
                  =dog.age
                %td
                  =dog.breed.name
                %td
                  =get_first_photo(dog)
                %td
                  =link_to "Conocer a #{dog.name}", user_dog_path(dog.user.id, dog.id)
    .col-md-4
      =link_to "Buscar para adoptar", "#", class: "btn btn-info big_button btn_white_font"
      %br
      %br
      = is_user_logged

app/views/layouts/application.haml
!!!
%html
  %head
    %title Llevame
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{:src => "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", :type => "text/javascript"}
    %script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}
  %body
    %nav.navbar.navbar-default.menu
      .container-fluid
        .navbar-header
          =link_to "Inicio", root_path, class: "navbar-brand"
          =link_to "Acerca de Nosotros", "#", class: "navbar-text"
          =link_to "Donaciones", "#", class: "navbar-text"
        .navbar-header.navbar-right
          - if user_signed_in?
            %p.navbar-text
              Bienvenido #{current_user.name}
            = link_to 'Cerrar sesion', destroy_user_session_path, :method => :delete, class: "navbar-text"
          - else
            %p
              = link_to 'Registrarse', new_user_registration_path, class: "navbar-text"
              = link_to 'Iniciar sesion', new_user_session_path, class: "navbar-text"
    .mycontainer
      = yield

app/views/photos/_form.haml
= form_for [@user, @dog, @photo], :html => { :role => "form", :multipart => true, id: "new-photo", class: "new_user_dog_photo dropzone"}, validate: true do |f|
  .photos
    %h4
      Sube hasta 5 fotos de #{@dog.name} para que las demas personas lo conozcan
      = link_to 'Continuar', user_dog_path(@user, @dog), class: "btn btn-success btn_white_font"
    #dropzonePreview
    %br


:javascript
  $(document).ready(function(){
    Dropzone.options.newPhoto = {
      //autoDiscover = false,
      //autoProcessQueue: false,
      uploadMultiple: true,
      parallelUploads: 5,
      maxFiles: 5,
      previewsContainer: '#dropzonePreview',
      paramName: "photos[]",

      // The setting up of the dropzone
      init: function() {
        var myDropzone = this;
            //now we will submit the form when the button is clicked

            //$("#sbmtbtn").on('click',function(e) {
              //e.preventDefault();
              //e.stopPropagation();
              //myDropzone.processQueue();
            // this will submit your form to the specified action path
              // after this, your whole form will get submitted with all the inputs + your files and the php code will remain as usual
        //REMEMBER you DON'T have to call ajax or anything by yourself, dropzone will take care of that

          } // init end
    };

  });

app/views/photos/new.haml
.container
  %h3 Siguen las fotos!
  =render 'form'